# Generated by Django 2.2.1 on 2019-05-15 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('imdb_rating', models.FloatField(max_length=1)),
                ('director', models.CharField(max_length=255)),
            ],
        ),
    ]
